Repository prgrms-fe-devcourse/FEDC2_TTaBong_Dali, pull requests merged in 2022-06, with the labels that each got.

#2 #1/프로젝트 개발 환경 초기화
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
  src/App.js
  src/App.jsx
  src/App.test.js
  src/components/Button/index.jsx
  src/components/Button/index.stories.jsx
  src/components/Button/style.jsx
  src/components/TestButton/stories/Button.jsx
  src/components/TestButton/stories/Button.stories.jsx
  src/components/TestButton/stories/button.css
  src/components/TestButton/stories/test.stories.jsx
  src/feature/User/Avatar/index.jsx
  src/feature/User/Avatar/index.stories.jsx
  src/feature/User/Avatar/style.jsx
  src/index.js
  src/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/NotFound/index.stories.jsx
  src/pages/NotFound/style.jsx
  src/reportWebVitals.js
  src/setupTests.js
  yarn.lock
Labels: feat, docs

#5 #4/ PR, issue template 설정
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#6 Fix/ 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
Labels: fix

#11 #3/style/global style
  .storybook/preview.js
  package.json
  src/App.jsx
  src/assets/background.png
  src/commons/constants/routes.js
  src/commons/style/GlobalStyle.jsx
  src/commons/style/themes.js
  src/components/Button/index.jsx
  src/components/Button/index.stories.jsx
  src/components/Button/style.jsx
  yarn.lock
Labels: style

#14 #13/feat/bottom bar
  src/assets/TTaBong_white.svg
  src/assets/icon_list_fill.svg
  src/assets/icon_ranking_fill.svg
  src/assets/icon_ranking_line.svg
  src/assets/icon_search_line.svg
  src/assets/icon_user_line.svg
  src/components/Icon/index.jsx
  src/components/Icon/index.stories.jsx
  src/components/Icon/style.jsx
  src/feature/BottomBar/index.jsx
  src/feature/BottomBar/index.stories.jsx
  src/feature/BottomBar/style.jsx
Labels: feat, 보통

#15 #12/Feat/main card
  .eslintrc.js
  public/background.png
  src/assets/avatar_default.svg
  src/assets/sympathy_ttabong.svg
  src/assets/ttabong_card.svg
  src/components/Avatar/index.jsx
  src/components/Avatar/index.stories.jsx
  src/components/Avatar/style.jsx
  src/components/Label/index.jsx
  src/components/Label/index.stories.jsx
  src/components/Label/style.jsx
  src/feature/MainFeed/MainCard/index.jsx
  src/feature/MainFeed/MainCard/index.stories.jsx
  src/feature/MainFeed/MainCard/style.jsx
  src/feature/User/Avatar/index.jsx
  src/feature/User/Avatar/index.stories.jsx
  src/feature/User/Avatar/style.jsx
Labels: feat, 보통

#17 #16/feat/header
  src/components/Avatar/index.jsx
  src/feature/Header/index.jsx
  src/feature/Header/index.stories.jsx
  src/feature/Header/style.jsx
Labels: feat, 보통

#25 #21/refactor/icon_2 : BottomBar 중점으로 Refactoring하기
  src/assets/icons/index.js
  src/components/Icon/index.jsx
  src/components/Icon/index.stories.jsx
  src/feature/BottomBar/index.jsx
Labels: refactor, 긴급

#24 #21/Refactor/ Icon & BottomBar 컴포넌트 props 관련 리팩터링
  .eslintrc.js
  src/assets/icon_list_fill.svg
  src/assets/icon_ranking_fill.svg
  src/assets/icon_ranking_line.svg
  src/assets/icon_search_line.svg
  src/assets/icon_user_line.svg
  src/assets/icons/TTaBong_white.svg
  src/assets/icons/icon_list_fill.svg
  src/assets/icons/icon_list_line.svg
  src/assets/icons/icon_ranking_fill.svg
  src/assets/icons/icon_ranking_line.svg
  src/assets/icons/icon_search_fill.svg
  src/assets/icons/icon_search_line.svg
  src/assets/icons/icon_user_fill.svg
  src/assets/icons/icon_user_line.svg
  src/assets/icons/index.js
  src/components/Icon/index.jsx
  src/components/Icon/index.stories.jsx
  src/components/Icon/style.jsx
  src/feature/BottomBar/index.jsx
  src/feature/BottomBar/index.stories.jsx
Labels: refactor, 보통

#30 #23/feat/banner 구현
  src/assets/icon_alarm_line.svg
  src/components/Badge/index.jsx
  src/components/Badge/index.stories.jsx
  src/components/Badge/style.jsx
  src/feature/Banner/index.jsx
  src/feature/Banner/index.stories.jsx
  src/feature/Banner/style.jsx
  src/feature/Header/index.jsx
  src/feature/Header/index.stories.jsx
  src/feature/Header/style.jsx
  src/hooks/useRafState.js
  src/hooks/useScroll.js
  src/hooks/useScrollDown.js
Labels: feat

#37 #20/feat/page template 2
  src/feature/BottomBar/style.jsx
  src/feature/Header/style.jsx
  src/pages/PageTemplate/index.jsx
  src/pages/PageTemplate/style.jsx
Labels: style, 긴급

#8 #7/feat/dummy data
  .eslintrc.js
  src/assets/data/dummyData.js
  src/commons/constants/index.js
  src/feature/TestApiComponent/index.jsx
Labels: feat, chore

#39 Feat/ UserInfoItem 구현
  src/components/UserInfoItem/index.jsx
  src/components/UserInfoItem/index.stories.jsx
  src/components/UserInfoItem/style.jsx
Labels: feat

#42 Fix/Router 버그 문제 해결
  src/feature/BottomBar/index.stories.jsx
Labels: fix, 긴급

#43 #22/feat/auth/LoginForm, RegisterForm 구현 (useForm hook)
  .eslintrc.js
  src/assets/icon_remove.svg
  src/assets/icon_search_blue.svg
  src/commons/constants/error.js
  src/commons/constants/string.js
  src/commons/style/GlobalStyle.jsx
  src/commons/style/themes.js
  src/components/Avatar/index.jsx
  src/components/Button/index.jsx
  src/components/Button/index.stories.jsx
  src/components/Button/style.jsx
  src/components/InputForm/index.jsx
  src/components/InputForm/index.stories.jsx
  src/components/InputForm/style.jsx
  src/components/Logo/index.jsx
  src/components/Logo/index.stories.jsx
  src/components/Logo/style.jsx
  src/feature/Header/index.jsx
  src/feature/Header/style.jsx
  src/feature/auth/LoginForm/index.jsx
  src/feature/auth/LoginForm/index.stories.jsx
  src/feature/auth/LoginForm/style.jsx
  src/feature/auth/RegisterForm/index.jsx
  src/feature/auth/RegisterForm/index.stories.jsx
  src/feature/auth/RegisterForm/style.jsx
  src/hooks/useForm.jsx
Labels: feat, 보통

#55 #52/feat/add issue template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, 긴급

#59 Refactor/ UserInfoItem 변수명 수정 및 버그 수정
  src/components/UserInfoItem/index.jsx
  src/components/UserInfoItem/index.stories.jsx
Labels: fix, refactor, 긴급

#49 #44/Feat/ RankFirstInfo 구현
  src/feature/rank/RankFirstInfo/index.jsx
  src/feature/rank/RankFirstInfo/index.stories.jsx
  src/feature/rank/RankFirstInfo/style.jsx
Labels: feat, 보통

#40 #34/feat/BaseCardContainer 구현 (base component)
  src/commons/constants/index.js
  src/commons/style/themes.js
  src/components/BaseCardContainer/index.jsx
  src/components/BaseCardContainer/index.stories.jsx
  src/components/BaseCardContainer/style.jsx
  src/utils/getHexToRgb.js
Labels: feat, refactor, 긴급

#47 #32/feat/CardDetail 컴포넌트 구현 및 기존 MainCard 컴포넌트 분리
  src/components/Divider/index.jsx
  src/components/Divider/index.stories.jsx
  src/components/Divider/style.jsx
  src/components/Image/index.jsx
  src/components/Image/index.stories.jsx
  src/components/Image/style.jsx
  src/components/Label/style.jsx
  src/feature/Cards/Card/index.jsx
  src/feature/Cards/Card/index.stories.jsx
  src/feature/Cards/Card/style.jsx
  src/feature/Cards/CardDetail/index.jsx
  src/feature/Cards/CardDetail/index.stories.jsx
  src/feature/Cards/CardDetail/style.jsx
  src/feature/Cards/Comment/index.jsx
  src/feature/Cards/Comment/index.stories.jsx
  src/feature/Cards/Comment/style.jsx
  src/feature/Cards/CommentList/index.jsx
  src/feature/Cards/CommentList/index.stories.jsx
  src/feature/Cards/CommentList/style.jsx
  src/feature/Cards/LabelList/index.jsx
  src/feature/Cards/LabelList/index.stories.jsx
  src/feature/Cards/LabelList/style.jsx
  src/feature/Cards/MainCard/index.jsx
  src/feature/Cards/MainCard/index.stories.jsx
  src/feature/Cards/MainCard/style.jsx
  src/feature/Cards/TTaBongerAndTTaBonged/index.jsx
  src/feature/Cards/TTaBongerAndTTaBonged/index.stories.jsx
  src/feature/Cards/TTaBongerAndTTaBonged/style.jsx
  src/utils/getDayString.js
  src/utils/getPxToRem.js
Labels: feat, refactor, 보통

#51 #18/feat/main feed page
  src/assets/background.png
  src/feature/Banner/style.jsx
  src/feature/Header/style.jsx
  src/hooks/useScroll.js
  src/hooks/useScrollDown.js
  src/pages/MainFeedPage/index.jsx
  src/pages/MainFeedPage/index.stories.jsx
  src/pages/MainFeedPage/style.jsx
  src/pages/PageTemplate/style.jsx
Labels: feat, 보통

#63 Feat/ 스토리북 뷰포트 추가
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: feat, chore, 긴급

#67 #66/fix/main feed page
  src/feature/Header/index.jsx
  src/pages/MainFeedPage/index.jsx
Labels: fix, 긴급

#71 Fix/useScroll consistent-return 관련 에러 해결
  src/hooks/useScroll.js
Labels: fix, 긴급

#65 #63/refactor/directory structure refactoring
  src/assets/images/background.png
  src/feature/pageTemplate/Banner/index.jsx
  src/feature/pageTemplate/Banner/index.stories.jsx
  src/feature/pageTemplate/Banner/style.jsx
  src/feature/pageTemplate/BottomBar/index.jsx
  src/feature/pageTemplate/BottomBar/index.stories.jsx
  src/feature/pageTemplate/BottomBar/style.jsx
  src/feature/pageTemplate/Header/index.jsx
  src/feature/pageTemplate/Header/index.stories.jsx
  src/feature/pageTemplate/Header/style.jsx
  src/feature/pageTemplate/PageTemplate/index.jsx
  src/feature/pageTemplate/PageTemplate/index.stories.jsx
  src/feature/pageTemplate/PageTemplate/style.jsx
  src/hooks/useScroll.js
  src/pages/MainFeedPage/index.jsx
Labels: refactor, 긴급

#75 Refactor/ 필수 사항 아닌 props들 isRequired 제거
  src/components/Avatar/index.jsx
  src/components/Logo/index.jsx
Labels: refactor, 긴급

#68 #48/feat/auth page
  package.json
  src/App.jsx
  src/apis/auth.js
  src/commons/constants/apis.js
  src/components/Logo/index.jsx
  src/feature/auth/LoginForm/index.jsx
  src/feature/auth/RegisterForm/index.jsx
  src/hooks/useForm.js
  src/pages/LoginPage/index.jsx
  src/pages/LoginPage/style.jsx
  src/pages/RegisterPage/index.jsx
  src/pages/RegisterPage/style.jsx
  src/pages/SignupPage/index.jsx
  src/pages/index.js
  src/utils/cookies.js
  yarn.lock
Labels: feat, 보통

#86 #77/style/GlobalFont 적용
  src/commons/style/GlobalStyle.jsx
  src/feature/auth/LoginForm/index.jsx
  src/feature/auth/RegisterForm/index.jsx
  src/index.css
  src/index.jsx
Labels: style, 보통

#87 #33/feat/search page
  src/App.jsx
  src/apis/users.js
  src/commons/constants/index.js
  src/components/Avatar/index.jsx
  src/components/BaseCardContainer/index.jsx
  src/components/BaseCardContainer/index.stories.jsx
  src/components/BaseCardContainer/style.jsx
  src/components/InputForm/index.jsx
  src/components/Logo/index.jsx
  src/components/Tab/index.jsx
  src/components/UserInfoItem/index.jsx
  src/feature/Cards/MainCard/index.jsx
  src/feature/Cards/MainCard/index.stories.jsx
  src/feature/Cards/MainCard/style.jsx
  src/feature/TestApiComponent/index.jsx
  src/feature/pageTemplate/PageTemplate/style.jsx
  src/pages/MainFeedPage/index.jsx
  src/pages/MainFeedPage/style.jsx
  src/pages/SearchPage/index.jsx
  src/pages/SearchPage/style.jsx
Labels: feat, refactor, 보통

#78 Feat/ Rank 페이지 구현
  src/pages/RankPage/index.jsx
  src/pages/RankPage/index.stories.jsx
  src/pages/RankPage/style.jsx
Labels: feat, 보통

#97 #96/refactor/various bug fix
  src/apis/index.js
  src/components/Logo/index.jsx
  src/feature/TestApiComponent/index.jsx
  src/pages/RankPage/index.jsx
Labels: fix, refactor, 긴급

#82 Feat/ ProfileEditPage 구현
  src/App.jsx
  src/apis/settings.js
  src/commons/constants/error.js
  src/commons/constants/string.js
  src/commons/style/GlobalStyle.jsx
  src/components/Button/index.jsx
  src/components/InputForm/index.jsx
  src/components/InputForm/style.jsx
  src/feature/auth/LoginForm/index.stories.jsx
  src/feature/auth/RegisterForm/index.stories.jsx
  src/feature/profile/ProfileEditForm/index.jsx
  src/feature/profile/ProfileEditForm/index.stories.jsx
  src/feature/profile/ProfileEditForm/style.jsx
  src/pages/ProfileEditPage/index.jsx
  src/pages/ProfileEditPage/style.jsx
  src/pages/index.js
Labels: feat, 보통

#101 #88/Feat/Context API를 통한 User 정보 전역상태관리
  src/App.jsx
  src/apis/auth.js
  src/contexts/UserProvider.jsx
  src/pages/LoginPage/index.jsx
  src/pages/RegisterPage/index.jsx
  src/routes/AuthRoute.jsx
  src/routes/ProtectedRoute.jsx
  src/routes/index.js
Labels: feat, 보통

#94 Modify/ CardDetail api 재 pr
  src/App.jsx
  src/apis/comments.js
  src/apis/like.js
  src/apis/notifications.js
  src/components/InputForm/index.jsx
  src/components/InputForm/style.jsx
  src/feature/Cards/Card/index.jsx
  src/feature/Cards/Card/style.jsx
  src/feature/Cards/CardDetail/index.jsx
  src/feature/Cards/CardDetail/style.jsx
  src/feature/Cards/Comment/index.jsx
  src/feature/Cards/TTaBongerAndTTaBonged/index.jsx
  src/pages/CardDetailPage/index.jsx
  src/pages/CardDetailPage/index.stories.jsx
Labels: 긴급

#95 #89/feat/image upload container
  src/assets/icons/icon_delete_line.svg
  src/assets/icons/icon_file_line.svg
  src/assets/icons/index.js
  src/feature/ttabong/ImageUploadContainer/index.jsx
  src/feature/ttabong/ImageUploadContainer/index.stories.jsx
  src/feature/ttabong/ImageUploadContainer/style.jsx
Labels: feat, 보통

#102 Feat/ 칭찬 사유 컴포넌트 구현
  src/feature/ttabong/ReasonContainer/index.jsx
  src/feature/ttabong/ReasonContainer/index.stories.jsx
  src/feature/ttabong/ReasonContainer/style.jsx
Labels: feat, 보통

#113 Refactor/ user => authUser 변수명 변경 및 로그인시 userId 받아오기
  src/contexts/UserProvider.jsx
  src/routes/AuthRoute.jsx
  src/routes/ProtectedRoute.jsx
Labels: fix, refactor, 긴급

#100 모달, 따봉모달 기본적인 구현 (아직 칭찬하기 페이지와의 연동은 배제)
  src/assets/icons/icon_check_white.svg
  src/assets/icons/index.js
  src/components/Modal/index.jsx
  src/components/Modal/index.stories.jsx
  src/components/Modal/style.jsx
  src/components/UserInfoItem/index.jsx
  src/components/UserInfoItem/index.stories.jsx
  src/feature/praise/CheckIcon/index.jsx
  src/feature/praise/CheckIcon/index.stories.jsx
  src/feature/praise/CheckIcon/style.jsx
  src/feature/praise/TTaBongModal/index.jsx
  src/feature/praise/TTaBongModal/index.stories.jsx
  src/feature/praise/TTaBongModal/style.jsx
Labels: feat, refactor, 보통

#114 Refactor/ Auth 상태에 따른 ProfileEditForm 수정 및 라우팅 처리
  src/App.jsx
  src/commons/style/GlobalStyle.jsx
  src/components/InputForm/index.jsx
  src/contexts/UserProvider.jsx
  src/feature/auth/LoginForm/index.jsx
  src/feature/auth/LoginForm/style.jsx
  src/feature/auth/RegisterForm/index.jsx
  src/feature/auth/RegisterForm/style.jsx
  src/feature/profile/ProfileEditForm/index.jsx
  src/pages/ProfileEditPage/index.jsx
Labels: feat, refactor, 보통

#109 CardDetail 전역 상태값 연동 작업
  src/apis/comments.js
  src/apis/like.js
  src/apis/notifications.js
  src/assets/icons/index.js
  src/assets/icons/sympathy_ttabong.svg
  src/feature/Cards/CardDetail/index.jsx
  src/pages/CardDetailPage/index.jsx
  src/utils/getDayString.js
Labels: feat, 보통

#111 Refactor/ 랭크페이지 최종
  src/apis/users.js
  src/commons/constants/index.js
  src/feature/rank/RankFirstInfo/index.jsx
  src/pages/RankPage/index.jsx
  src/pages/RankPage/style.jsx
Labels: feat, 보통

#105 Feat/ 알람 페이지 구현
  src/App.jsx
  src/feature/Alarm/AlarmItem/index.jsx
  src/feature/Alarm/AlarmItem/index.stories.jsx
  src/feature/Alarm/AlarmItem/style.jsx
  src/feature/Alarm/AlarmSection/index.jsx
  src/feature/Alarm/AlarmSection/index.stories.jsx
  src/feature/Alarm/AlarmSection/style.jsx
  src/pages/AlarmPage/index.jsx
  src/pages/AlarmPage/index.stories.jsx
  src/pages/AlarmPage/style.jsx
Labels: feat

#117 Fix/ 모달창 푸시 안된 버그 픽스 커밋 재pr
  src/feature/praise/CheckIcon/style.jsx
  src/feature/praise/TTaBongModal/index.jsx
Labels: fix, 긴급

#115 Feat/ NotFoundPage
  src/App.jsx
  src/assets/images/notfound.png
  src/pages/NotFound/index.jsx
  src/pages/NotFound/index.stories.jsx
  src/pages/NotFound/style.jsx
  src/pages/NotFoundPage/index.jsx
  src/pages/NotFoundPage/index.stories.jsx
  src/pages/NotFoundPage/style.jsx
  src/pages/index.js
Labels: feat, 보통

#122 Feat/MainCard Navigate 로직 수정
  src/feature/Cards/MainCard/index.jsx
Labels: fix, 긴급

#124 폴더 이름 변경
  src/feature/Alarm/AlarmItem/index.jsx
  src/feature/Alarm/AlarmItem/index.stories.jsx
  src/feature/Alarm/AlarmItem/style.jsx
  src/feature/Alarm/AlarmSection/index.jsx
  src/feature/Alarm/AlarmSection/index.stories.jsx
  src/feature/Alarm/AlarmSection/style.jsx
  src/feature/Cards/Card/index.jsx
  src/feature/Cards/Card/index.stories.jsx
  src/feature/Cards/Card/style.jsx
  src/feature/Cards/CardDetail/index.jsx
  src/feature/Cards/CardDetail/index.stories.jsx
  src/feature/Cards/CardDetail/style.jsx
  src/feature/Cards/Comment/index.jsx
  src/feature/Cards/Comment/index.stories.jsx
  src/feature/Cards/Comment/style.jsx
  src/feature/Cards/CommentList/index.jsx
  src/feature/Cards/CommentList/index.stories.jsx
  src/feature/Cards/CommentList/style.jsx
  src/feature/Cards/LabelList/index.jsx
  src/feature/Cards/LabelList/index.stories.jsx
  src/feature/Cards/LabelList/style.jsx
  src/feature/Cards/MainCard/index.jsx
  src/feature/Cards/MainCard/index.stories.jsx
  src/feature/Cards/MainCard/style.jsx
  src/feature/Cards/TTaBongerAndTTaBonged/index.jsx
  src/feature/Cards/TTaBongerAndTTaBonged/index.stories.jsx
  src/feature/Cards/TTaBongerAndTTaBonged/style.jsx
  src/feature/cards/MainCard/index.jsx
Labels: fix, 긴급

#128 Refactor/ UI 수정
  src/components/UserInfoItem/style.jsx
  src/pages/RankPage/index.jsx
  src/pages/RankPage/style.jsx
Labels: refactor, 긴급

#130 #125/fix/바텀바 링크 관련 버그 해결
  src/feature/pageTemplate/BottomBar/index.jsx
  src/pages/AlarmPage/index.jsx
Labels: fix, 긴급

#133 #83/feat/유저 프로필 페이지 1차 구현
  src/App.jsx
  src/assets/icons/icon_logout.svg
  src/assets/icons/index.js
  src/components/Button/style.jsx
  src/components/Divider/index.jsx
  src/components/Icon/index.jsx
  src/components/Icon/index.stories.jsx
  src/feature/Cards/ProfileCard/index.jsx
  src/feature/Cards/ProfileCard/index.stories.jsx
  src/feature/Cards/ProfileCard/style.jsx
  src/pages/UserProfilePage/index.jsx
  src/pages/UserProfilePage/index.stories.jsx
  src/pages/UserProfilePage/style.jsx
Labels: feat, 보통

#131 Modify/ authUser 변수명 수정
  src/apis/comments.js
  src/apis/like.js
  src/apis/notifications.js
  src/feature/alarm/AlarmItem/index.jsx
  src/pages/AlarmPage/index.jsx
  src/pages/AlarmPage/style.jsx
  src/pages/CardDetailPage/index.jsx
Labels: fix, 긴급

#129 Feat/ LoginForm, RegisterForm validation 로직 추가
  src/apis/api.js
  src/apis/auth.js
  src/commons/constants/error.js
  src/commons/constants/string.js
  src/feature/auth/RegisterForm/index.jsx
  src/pages/AlarmPage/index.jsx
  src/pages/LoginPage/index.jsx
  src/pages/RegisterPage/index.jsx
Labels: feat, 보통

#136 #134/fix/유저 프로필 페이지, 바텀바 버그 픽스
  src/assets/icons/index.js
  src/feature/pageTemplate/BottomBar/index.jsx
  src/pages/UserProfilePage/index.jsx
Labels: fix, 긴급

#132 #119/ 검색페이지 스타일 수정, 버그 픽스, 버튼 기능 추가
  src/components/InputForm/index.jsx
  src/feature/cards/MainCard/index.jsx
  src/feature/praise/TTaBongModal/index.jsx
  src/pages/SearchPage/index.jsx
  src/pages/SearchPage/index.stories.jsx
  src/pages/SearchPage/style.jsx
Labels: fix, refactor, style, chore

#137 Feat/ 따봉페이지 구현 (기능 완료)
  src/components/Avatar/index.jsx
  src/components/Avatar/style.jsx
  src/components/Button/style.jsx
  src/components/InputForm/style.jsx
  src/components/Modal/style.jsx
  src/components/UserInfoItem/index.jsx
  src/feature/cards/TTaBongerAndTTaBonged/index.jsx
  src/feature/ttabong/CheckIcon/index.jsx
  src/feature/ttabong/CheckIcon/index.stories.jsx
  src/feature/ttabong/CheckIcon/style.jsx
  src/feature/ttabong/ImageUploadContainer/index.jsx
  src/feature/ttabong/LabelList/index.jsx
  src/feature/ttabong/ReasonContainer/index.jsx
  src/feature/ttabong/TTaBongModal/index.jsx
  src/feature/ttabong/TTaBongModal/index.stories.jsx
  src/feature/ttabong/TTaBongModal/style.jsx
  src/feature/ttabong/index.js
  src/pages/TTaBongPage/index.jsx
  src/pages/TTaBongPage/index.stories.jsx
  src/pages/TTaBongPage/style.jsx
Labels: feat, 긴급

#145 #143/ 따봉 페이지 업그레이드
  src/components/BaseCardContainer/index.jsx
  src/feature/ttabong/ReasonContainer/style.jsx
  src/feature/ttabong/TTaBongModal/index.jsx
  src/pages/TTaBongPage/index.jsx
  src/pages/TTaBongPage/style.jsx
Labels: refactor, 보통

#148 Fix/ Image post 객체에 붙이기
  src/feature/ttabong/ImageUploadContainer/index.jsx
  src/pages/TTaBongPage/index.jsx
Labels: fix, 긴급

#153 Refactor/limit값 수정 및 Announce 추가
  src/pages/MainFeedPage/index.jsx
  src/pages/MainFeedPage/style.jsx
Labels: refactor, 보통

#142 Feat/ AlarmPage Protected Route 작업
  src/App.jsx
  src/commons/constants/error.js
  src/feature/auth/LoginForm/index.jsx
  src/feature/auth/RegisterForm/index.jsx
  src/feature/pageTemplate/Header/index.jsx
  src/feature/pageTemplate/Header/style.jsx
  src/pages/index.js
  src/routes/ProtectedRoute.jsx
Labels: feat, 보통

#156 Fix/ Post Api 수정
  src/apis/posts.js
Labels: fix, 긴급

#161 Feat/ Profile Edit 페이지에 프로필 이미지 편집 추가
  src/apis/users.js
  src/feature/profile/ProfileEditForm/index.jsx
  src/feature/profile/ProfileEditForm/style.jsx
  src/pages/ProfileEditPage/index.jsx
Labels: feat, 긴급

#166 #160/feat/스피너를 붙이고, 스타일을 수정하고, 약간의 로직을 뚞딲뚞딲
  src/components/Spinner/style.jsx
  src/components/Tab/style.jsx
  src/components/UserInfoItem/style.jsx
  src/feature/pageTemplate/Banner/style.jsx
  src/feature/pageTemplate/BottomBar/index.jsx
  src/feature/pageTemplate/Header/index.jsx
  src/feature/pageTemplate/Header/style.jsx
  src/feature/pageTemplate/PageTemplate/style.jsx
  src/pages/RankPage/index.jsx
  src/pages/RankPage/style.jsx
  src/pages/SearchPage/index.jsx
  src/pages/UserProfilePage/index.jsx
  src/pages/UserProfilePage/style.jsx
Labels: feat, refactor, style, 보통

#171 Feat/Toast Component 구성
  package.json
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/logo192_.png
  public/manifest.json
  src/components/Toast/ToastItem.jsx
  src/components/Toast/ToastManager.jsx
  src/components/Toast/index.jsx
  src/components/Toast/style.jsx
  src/hooks/useTimeOut.js
  yarn.lock
Labels: feat, 보통

#175 #170/프로필 편집 페이지의 이미지업로드컨테이너 수정
  src/assets/icons/icon_file_gray.svg
  src/assets/icons/index.js
  src/components/Icon/index.stories.jsx
  src/components/ImageUploadContainer/index.jsx
  src/components/ImageUploadContainer/index.stories.jsx
  src/components/ImageUploadContainer/style.jsx
  src/feature/profile/ProfileEditForm/index.jsx
  src/feature/profile/ProfileEditForm/style.jsx
  src/feature/ttabong/index.js
  src/pages/TTaBongPage/index.jsx
Labels: refactor, style, 보통

#179 Fix/ 따봉드따봉러 버그수정
  src/feature/cards/MainCard/index.jsx
  src/feature/cards/TTaBongerAndTTaBonged/index.jsx
  src/pages/CardDetailPage/index.jsx
Labels: fix, 긴급

#182 Feat/메인카드에서 빅 따봉 및 라벨리스트 보일수 있게 구현
  src/feature/cards/MainCard/index.jsx
  src/feature/cards/MainCard/style.jsx
Labels: feat

#183 Refactor/ alert -> Toast로 바꾸기
  src/commons/constants/error.js
  src/commons/constants/string.js
  src/pages/CardDetailPage/index.jsx
  src/pages/LoginPage/index.jsx
  src/pages/MainFeedPage/index.jsx
  src/pages/ProfileEditPage/index.jsx
  src/pages/RegisterPage/index.jsx
  src/pages/TTaBongPage/index.jsx
  src/pages/UserProfilePage/index.jsx
Labels: refactor, 보통

#190 Feat/avatar border 컴포넌트 구현
  src/components/AvatarBorder/index.jsx
  src/components/AvatarBorder/index.stories.jsx
  src/components/AvatarBorder/style.jsx
  src/feature/pageTemplate/Banner/index.jsx
  src/feature/pageTemplate/Banner/style.jsx
  src/feature/pageTemplate/Header/index.jsx
Labels: feat, refactor, 긴급

#196 #192/style/토스트 디자인 변경 및 메인카드 디자인 변경
  src/commons/constants/error.js
  src/components/Toast/style.jsx
  src/pages/MainFeedPage/index.jsx
  src/pages/MainFeedPage/style.jsx
Labels: style, 보통

#200 Chore/토스트 문구 수정
  src/commons/constants/error.js
  src/commons/constants/string.js
  src/pages/UserProfilePage/index.jsx
Labels: style, 보통

#202 Feat/ UserProfile에 카드 이미지 넣기
  src/feature/Cards/ProfileCard/index.jsx
Labels: feat

#204 Feat/ 코멘트시 아바타 이미지 추가
  src/components/InputForm/index.jsx
  src/feature/cards/CardDetail/index.jsx
  src/feature/cards/CardDetail/style.jsx
  src/feature/cards/CommentList/style.jsx
  src/pages/CardDetailPage/index.jsx
Labels: feat, 긴급

#207 Delete/ 사용하지 않는 import 삭제
  src/feature/Cards/ProfileCard/index.jsx
Labels: refactor, 긴급

#209 Feat/ netlify 설정 추가
  netlify.toml
Labels: feat

#211 Fix/ ignorecase false
  src/feature/cards/ProfileCard/index.jsx
  src/feature/cards/ProfileCard/index.stories.jsx
  src/feature/cards/ProfileCard/style.jsx
Labels: fix
